#index:
#    path: /
#    controller: App\Controller\DefaultController::index

_error404:
  path: /{wildcard}
  controller: App\Controller\DefaultController::error404
  requirements:
      wildcard: ".*"