name: Symfony

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --no-scripts
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Create Database
      run: |
        mkdir -p data
        touch data/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
      run: vendor/bin/phpunit
    - name: Deploy Symfony App
      env:
        APP_ENV: prod
        DATABASE_URL: mysql://administrator_hbr:HandballRochettois73@localhost:3306/handballrochettois?serverVersion=mariadb-10.11.1&charset=utf8mb4
      run: |
        php bin/console cache:clear --no-warmup --env=prod
        php bin/console doctrine:migrations:migrate --no-interaction --env=prod
        php bin/console assets:install public --env=prod
